<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="PRESENTACION.Carrito" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="StyleSheet1.css" rel="stylesheet" />
    <style type="text/css">
        #MenuPrincipal{
            width: 100%;
            height: 100px;
            color: black;
        }
        #MenuPrincipal table tr td{
            text-align: center;
        }
        #MenuPrincipal table tr td a{
            text-decoration: none;
        }
        .tablacabecera {
            width: 100%;
        }
        .style-tablaenblanco {
            width: 137px;
        }
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 638px;
        }
        .auto-style3 {
            width: 638px;
            height: 219px;
        }
        .auto-style4 {
            height: 58px;
            width: 95%;
        }
        .auto-style5 {
            width: 107px;
        }
        .auto-style6 {
            width: 116%;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div id="MenuPrincipal" class="auto-style4">
            <table class="tablacabecera">
                <tr>
                    <td >
                        <asp:Label ID="lblUsuario" runat="server"></asp:Label>
                    </td>
                    <td class="auto-style5" >
                        <asp:LinkButton ID="LinkButton1" runat="server" OnClick="LinkButton1_Click">Pagina Principal</asp:LinkButton>
                    </td>
                    <td class="style-tablaenblanco" >&nbsp;</td>
                    <td class="style-tablaenblanco" ></td>
                    <td class="style-tablaenblanco" ></td>
                    <td class="style-tablaenblanco" >
                        <asp:Label ID="lblIdUsuario" runat="server" Visible="False"></asp:Label>
                    </td>
                </tr>
            </table>
            <br />
            <table class="auto-style1">
                <tr>
                    <td class="auto-style3">
                        <asp:GridView ID="gvSubVenta" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" Height="196px" Width="540px" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" OnRowDeleting="gvSubVenta_RowDeleting" PageSize="5">
                            <Columns>
                                <asp:TemplateField HeaderText="Descripcion">
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Descripcion") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Cantidad">
                                    <ItemTemplate>
                                        <asp:TextBox ID="TextBox1" runat="server" Height="16px" Width="73px"></asp:TextBox>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Precio">
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("PrecioVenta") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Sub total">
                                    <ItemTemplate>
                                        <asp:Label ID="Label4" runat="server"></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                            <RowStyle ForeColor="#003399" BackColor="White" />
                            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                            <SortedAscendingCellStyle BackColor="#EDF6F6" />
                            <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                            <SortedDescendingCellStyle BackColor="#D6DFDF" />
                            <SortedDescendingHeaderStyle BackColor="#002876" />
                        </asp:GridView>
                        <br />
                        <table class="auto-style6">
                            <tr>
                                <td>
                                    <asp:Button ID="btnCalcularPrecio" runat="server" Text="Calcular precio" OnClick="btnCalcularPrecio_Click" />
                                </td>
                                <td>
                                    <asp:Button ID="btnRealizarCompra" runat="server" Text="Realizar compra" OnClick="btnRealizarCompra_Click" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label ID="lbltotal" runat="server"></asp:Label>
                                </td>
                                <td>
                                    <asp:Label ID="lblError" runat="server"></asp:Label>
                                </td>
                            </tr>
                        </table>
                        <br /></td>
                </tr>
                <tr>
                    <td class="auto-style2">
                        &nbsp;</td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
