<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Categorias.aspx.cs" Inherits="PRESENTACION.PaginaAdmin.AgregarCategoria" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="../StyleSheet1.css" rel="stylesheet" />
    <style type="text/css">
        #MenuPrincipal{
            width: 100%;
            height: 100px;
            color: black;
        }
        #MenuPrincipal table tr td{
            text-align: center;
        }
        #MenuPrincipal table tr td a{
            text-decoration: none;
        }
        .tablacabecera {
            width: 100%;
        }
        .style-tablaenblanco {
            width: 137px;
        }
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            width: 108px;
        }
        .auto-style4 {
            width: 254px;
        }
        .auto-style6 {
            width: 181px;            
        }
        .auto-style8 {
            width: 83%;
        }
        .auto-style9 {
            width: 82%;
        }
        .auto-style10 {
            width: 43%;
        }
        .auto-style12 {
            width: 71%;
        }
        .auto-style13 {
            width: 29%;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <table class="tablacabecera">
                <tr>
                    <td class="auto-style10">
                        <asp:LinkButton ID="lkbPaginaPrincipal" runat="server" OnClick="lkbPaginaPrincipal_Click">Pagina Principal</asp:LinkButton>
                    </td>
                    <td class="auto-style13">
                        <asp:LinkButton ID="lkbArticulos" runat="server" OnClick="lkbArticulos_Click">Articulos</asp:LinkButton>
                    </td>
                    <td class="auto-style12">
                        <asp:LinkButton ID="lkbUsuarios" runat="server" OnClick="lkbUsuarios_Click">Usuarios</asp:LinkButton>
                    </td>
                    <td class="auto-style9">
                        <asp:LinkButton ID="lkbProveedores" runat="server" OnClick="lkbProveedores_Click">Proveedores</asp:LinkButton>
                    </td>
                    <td class="auto-style9"></td>
                    <td class="auto-style9">
                        <asp:Label ID="lblAdmin" runat="server" Visible="False"></asp:Label>
                    </td>
                </tr>
            </table>
        <div>
            <br />
            <table class="auto-style2">
                <tr>
                    <td class="auto-style4">Descripcion:
                        <asp:TextBox ID="txtDescripcionBuscar" runat="server" Width="156px"></asp:TextBox>
                    </td>
                    <td>
                        <asp:Button ID="Button3" runat="server" Text="Buscar" OnClick="Button3_Click" />
                    </td>
                </tr>
            </table>
            <asp:GridView ID="gv_Categoria" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="gv_Categoria_RowCancelingEdit"  OnRowEditing="gv_Categoria_RowEditing" OnRowUpdating="gv_Categoria_RowUpdating" OnRowDeleting="gv_Categoria_RowDeleting" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4">
                <Columns>
                    <asp:TemplateField HeaderText="Id">
                        <EditItemTemplate>
                            <asp:Label ID="lbl_eit_ID" runat="server" Text='<%# Bind("ID") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_ID" runat="server" Text='<%# Bind("ID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripcion">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Descripcion" runat="server" Text='<%# Bind("DescripcionC") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Descripcion" runat="server" Text='<%# Bind("DescripcionC") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Estado">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Estado" runat="server" Text='<%# Bind("Estado") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Estado" runat="server" Text='<%# Bind("Estado") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                <RowStyle BackColor="White" ForeColor="#003399" />
                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                <SortedAscendingCellStyle BackColor="#EDF6F6" />
                <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                <SortedDescendingCellStyle BackColor="#D6DFDF" />
                <SortedDescendingHeaderStyle BackColor="#002876" />
            </asp:GridView>
            <br />
            
            <br />
            <table class="auto-style2">                
                <tr>
                    <td colspan="2">Agregar Categoria Nueva</td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">Descripcion</td>
                    <td class="auto-style6">
                        <asp:TextBox ID="txt_Descripcion" runat="server"></asp:TextBox><br />
                    </td>
                    <td class="auto-style8">
                        
                    </td>                    
                </tr>
                <tr>
                    <td class="auto-style3">Estado</td>
                    <td class="auto-style6">
                        <asp:DropDownList ID="ddl_Estado" runat="server">
                            <asp:ListItem>True</asp:ListItem>
                            <asp:ListItem>False</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                    <td class="auto-style8">
                        &nbsp;</td>                    
                </tr>
                <tr>
                    <td class="auto-style3">
                        <asp:Button ID="btn_AgregarCategoria" runat="server" Text="Agregar" OnClick="btn_AgregarCategoria_Click" />
                    </td>
                    <td class="auto-style6">
                        <asp:Button ID="Button2" runat="server" Text="Salir" Width="51px" OnClick="Button2_Click" />
                    </td>
                    <td>
                        <asp:Label ID="lbl_Mensaje" runat="server"></asp:Label>
                    </td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
