<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Proveedores.aspx.cs" Inherits="PRESENTACION.PaginaAdmin.Proveedores" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link href="../StyleSheet1.css" rel="stylesheet" />
    <style type="text/css">
        #MenuPrincipal{
            width: 100%;
            height: 100px;
            color: black;
        }
        #MenuPrincipal table tr td{
            text-align: center;
        }
        #MenuPrincipal table tr td a{
            text-decoration: none;
        }
        .tablacabecera {
            width: 100%;
        }
        .style-tablaenblanco {
            width: 137px;
        }
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            width: 254px;
        }
        .auto-style4 {
            height: 23px;
        }
        </style>
</head>
<link href="StyleSheet1.css" rel="stylesheet" />
<body>
    <form id="form1" runat="server">
        
        <div>
            <table class="tablacabecera">
                <tr>
                    <td class="auto-style8">
                        <asp:LinkButton ID="lkbPaginaPrincipal" runat="server" OnClick="lkbPaginaPrincipal_Click">Pagina Principal</asp:LinkButton>
                    </td>
                    <td class="auto-style9">
                        <asp:LinkButton ID="lkbArticulos" runat="server" OnClick="lkbArticulos_Click">Articulos</asp:LinkButton>
                    </td>
                    <td class="auto-style9">
                        <asp:LinkButton ID="lkbUsuarios" runat="server" OnClick="lkbUsuarios_Click">Usuarios</asp:LinkButton>
                    </td>
                    <td class="auto-style9">
                    </td>
                    <td class="auto-style9"></td>
                    <td class="auto-style9">
                        <asp:Label ID="lblAdmin" runat="server" Visible="False"></asp:Label>
                    </td>
                </tr>
            </table><br />
            <br />
            <table class="auto-style2">
                <tr>
                    <td class="auto-style3">Descripcion:
                        <asp:TextBox ID="txtBuscarProveedor" runat="server" Width="156px"></asp:TextBox>
                    </td>
                    <td>
                        <asp:Button ID="Button3" runat="server" Text="Buscar" OnClick="Button3_Click" />
                    </td>
                </tr>
            </table>
            <asp:GridView ID="grid_Proveedor" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="grid_Proveedor_RowCancelingEdit" OnRowEditing="grid_Proveedor_RowEditing" OnRowUpdating="grid_Proveedor_RowUpdating" OnRowDeleting="grid_Proveedor_RowDeleting" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4">
                <Columns>
                    <asp:TemplateField HeaderText="Id">
                        <EditItemTemplate>
                            <asp:Label ID="lbl_eit_Id" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Id" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripcion">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Descripcion" runat="server" Text='<%# Bind("DescripcionP") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Descripcion" runat="server" Text='<%# Bind("DescripcionP") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Direccion">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Direccion" runat="server" Text='<%# Bind("Direccion") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Direccion" runat="server" Text='<%# Bind("Direccion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Telefono">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Telefono" runat="server" Text='<%# Bind("Telefono") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Telefono" runat="server" Text='<%# Bind("Telefono") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Mail">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Mail" runat="server" Text='<%# Bind("Mail") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Mail" runat="server" Text='<%# Bind("Mail") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Estado">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_eit_Estado" runat="server" Text='<%# Bind("Estado") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_it_Estado" runat="server" Text='<%# Bind("Estado") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                <RowStyle BackColor="White" ForeColor="#003399" />
                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                <SortedAscendingCellStyle BackColor="#EDF6F6" />
                <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                <SortedDescendingCellStyle BackColor="#D6DFDF" />
                <SortedDescendingHeaderStyle BackColor="#002876" />
            </asp:GridView>
            <br />
            <br />
            <table class="auto-style2">
                <tr>
                    <td>Descripcion</td>
                    <td>
                        <asp:TextBox ID="txt_Descripcion" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>Direccion</td>
                    <td>
                        <asp:TextBox ID="txt_Direccion" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>Telefono</td>
                    <td>
                        <asp:TextBox ID="txt_Telefono" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>Mail</td>
                    <td>
                        <asp:TextBox ID="txt_Mail" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>Estado</td>
                    <td>
                        <asp:DropDownList ID="ddl_Estado" runat="server">
                            <asp:ListItem>True</asp:ListItem>
                            <asp:ListItem>False</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Button ID="btn_Agregar" runat="server" Text="Agregar" OnClick="btn_Agregar_Click" />
                    </td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style4">
                        &nbsp;</td>
                    <td class="auto-style4">
                        &nbsp;</td>
                </tr>
            </table>
        </div>
        <p>
                        <asp:Label ID="lbl_Mensaje" runat="server"></asp:Label>
                    </p>
        <p>
                        <asp:Label ID="lbl_Data" runat="server"></asp:Label>
                    </p>
    </form>
</body>
</html>
